In [1]:
import numpy as np

In [150]:
num = 5
e = np.array([3*e+1 for e in range (num)])
a1 = np.array([a for a in range (num)])
a2 = np.array([2*a+2 for a in range (num)])
a3 = np.array([np.random.randint(0, 5) for a in range (num)])
alla = np.array([a1, a2, a3]).T
A = np.hstack([np.ones((len(e), 1)), alla[:, 0:3]])
print(A)
print(np.linalg.det(A.T@A), "\n")

Ainv = np.linalg.inv(A.T @ A) @ A.T
x2 = Ainv @ e
print(x2)
print(A@x2)

x1, err, _, _ = np.linalg.lstsq(A, e, rcond=None) #prefer this one
print(x1, err)
print(A@x1)

[[ 1.  0.  2.  0.]
 [ 1.  1.  4.  4.]
 [ 1.  2.  6.  0.]
 [ 1.  3.  8.  4.]
 [ 1.  4. 10.  4.]]
-2.2737367544323307e-12 

[64.96875  -3.78125  -1.609375  0.      ]
[61.75 54.75 47.75 40.75 33.75]
[-7.77777778e-01  1.22222222e+00  8.88888889e-01  4.29066048e-17] []
[ 1.  4.  7. 10. 13.]


In [147]:
print(np.linspace(10, 8, 10))

[10.          9.77777778  9.55555556  9.33333333  9.11111111  8.88888889
  8.66666667  8.44444444  8.22222222  8.        ]
