In [1]:
import numpy as np
import pandas as pd

In [10]:
Jlist10 = pd.read_csv('Jlist_10.txt', sep = ' ', header = 0)
Jlist20 = pd.read_csv('Jlist_20.txt', sep = ' ', header = 0)

In [11]:
avg10 = np.zeros((3, 4))
avg20 = np.zeros((3, 4))
std10 = np.zeros((3, 4))
std20 = np.zeros((3, 4))
for i in range (3):
    a = np.average(Jlist10[5*i:5*i+5], axis=0)
    astd = np.std(Jlist10[5*i:5*i+5], axis=0)
    b = np.average(Jlist20[5*i:5*i+5], axis=0)
    bstd = np.std(Jlist20[5*i:5*i+5], axis=0)
    avg10[i] = a[2:6]
    avg20[i] = b[2:6]
    std10[i] = astd[2:6]
    std20[i] = bstd[2:6]

In [12]:
print(avg10)
print(std10)
print(avg20)
print(std20)

[[ 3.62446758  1.11266113  0.          0.        ]
 [ 5.16544711  1.15087916 -0.03599717  0.        ]
 [ 6.83094102  1.16651513  0.01100897 -0.05329765]]
[[0.07072301 0.00044258 0.         0.        ]
 [0.16602876 0.00370956 0.00272357 0.        ]
 [0.16353934 0.00319768 0.00341563 0.00148761]]
[[            nan             nan             nan             nan]
 [            nan             nan             nan             nan]
 [ 5.18725966e+01  1.27601351e+00 -7.83649269e-02 -3.43523386e-02]]
[[4.25097207e-01 7.02143259e-04 0.00000000e+00 0.00000000e+00]
 [1.40864795e-01 2.76000000e-07 2.05664150e-04 0.00000000e+00]
 [2.31812416e-01 1.92634849e-03 1.10414917e-03 7.64133364e-04]]
